sudo: false
language: python
python:
 - 2.7
 - 3.5
 - 3.6
 - 3.7
install:
 - pip install pytest coveralls pytest-cov
 - python setup.py develop
script: 
    py.test --cov language_tags --cov-report term-missing tests
after_success:
    coveralls
